### ISSUE TITLE
Remains of a merge conflict causing matlab errors:

### ISSUE THREAD

**Issue by richardbeare** [DevelopmentalImagingMCRI/freesurfer_statsurf_display#2]
There are merge conflict markers [here](https://github.com/DevelopmentalImagingMCRI/freesurfer_statsurf_display/blob/7b1b54c635fe9852e38d528cc92e5d7078c4067e/freesurfer_statsurf_plot.m#L198)

Could be others - haven't checked.

**Comment by richardbeare** [comment]
@chrisadamsonmcri - there's been a merge problem somewhere...

**Comment by chrisadamsonmcri** [comment]
No problems now. Thanks richard.
