### ISSUE TITLE
how to solve the problem with example ?

### ISSUE THREAD

**Issue by wangkangcheng** [DevelopmentalImagingMCRI/freesurfer_statsurf_display#3]
Hi 
  I try to use this toolbox with an example from https://developmentalimagingmcri.github.io/freesurfer_statsurf_display/using/ . But it reports error below. Could you help me to solve it ?

thanks 

RegionMask = cell(1, 2);

for z = 1:2
	RegionMask{z} = true(31, 1);
end

freesurfer_statsurf_fsrgb(RegionMask, 'dkt')
Error using annotation (line 106)
X and Y values must be between 0 and 1

Error in freesurfer_statsurf_plot (line 268)
	annotation('textarrow', XX, YY, 'String', 'Medial', T{:}, 'TextRotation', 90);

Error in freesurfer_statsurf_fsrgb (line 77)
freesurfer_statsurf_plot(FSAverageV, FSAverageF, FaceVertexCData, FreesurferSeedType, ...

**Comment by chrisadamsonmcri** [comment]
Fixed in ca51799195c4cf12210e728233f74644b7c6cda6
