### ISSUE TITLE
what is the option for different  colorbar?

### ISSUE THREAD

**Issue by wangkangcheng** [DevelopmentalImagingMCRI/freesurfer_statsurf_display#4]
Hi
  Can I change the default colorbar to another one in freesurfer_statsurf_p ?
thanks 

P = cell(1, 2);
T = cell(1, 2);

for z = 1:2
	P{z} = rand(31, 1) * 0.075;
	T{z} = rand(31, 1) * 5 - 3;
end

freesurfer_statsurf_p(P, T, 'dkt','MainTitle','test','NoLabels',true,'SurfType','inflated');

**Comment by chrisadamsonmcri** [comment]
In the p-value script there is no option to change the colormaps, but you are free to modify the script if you want. The colormaps are formed in lines 83 through 94. I use cool and hot to form the negative/positive p-value colours.

**Comment by chrisadamsonmcri** [comment]
Added the 'PosColorCMAP' and 'NegColorCMAP' options in freesurfer_statsurf_p
